#!/usr/bin/env python
# coding: utf-8

# In[1]:


import sklearn
import numpy as np


# In[1]:


import sklearn
import numpy as np


# In[2]:


#breast cancer data loading
from sklearn.datasets import load_breast_cancer


# Load dataset
data = load_breast_cancer()


# In[3]:


#The data variable represents a Python object that works like a dictionary. 
#The important dictionary keys to consider are the classification label names (target_names), the actual labels (target), the attribute/feature names (feature_names), and the attributes (data).
label_names = data['target_names']
labels = data['target']
feature_names = data['feature_names']
features = data['data']


# In[4]:


# Look at our data
print(label_names)
print(labels[0])
print(feature_names[0])
print(features[0])


# In[23]:


from sklearn.model_selection import train_test_split


# Split our data
train, test, train_labels, test_labels = train_test_split(features,
                                                          labels,
                                                          test_size=0.33,
                                                          random_state=42)


# In[24]:


from sklearn.naive_bayes import GaussianNB


# Initialize our classifier
gnb = GaussianNB()

# Train our classifier
model = gnb.fit(train, train_labels)


# In[25]:


# Make predictions
preds = gnb.predict(test)
print(preds)


# In[30]:


test_1 = np.array(test_labels)
accuracy_array = preds == test_1


# In[31]:


accuracy_score = np.mean(accuracy_array)


# In[32]:


accuracy_score


# In[ ]:




